name: CI

on:
  push:
    branches:
      - master
      - v4
    tags:
      - '*'
  pull_request:
  schedule:
    - cron:  '0 4 * * 5' # Fridays at 4am

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test:ember

  test-no-lock:
    name: Floating Dependencies
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false
      - name: Test
        run: yarn test:ember

  test-try:
    name: Scenario ${{ matrix.scenario }}, BS${{ matrix.bootstrap }}, ${{ matrix.browser}}
    runs-on: ubuntu-latest
    timeout-minutes: 14
    continue-on-error: ${{ matrix.allow-failure || false }}
    needs:
      - test
    strategy:
      fail-fast: false
      matrix:
        allow-failure:
          - false
        scenario:
          - ember-lts-3.16
          - ember-lts-3.20
          - ember-lts-3.24
          - ember-lts-3.28
          #- ember-release
          #- ember-beta
          #- ember-canary
          - ember-default-with-jquery
          - ember-classic
          - embroider-safe
          - embroider-optimized
        bootstrap:
          - 3
          - 4
          - 5
        browser:
          - Chrome
        include:
          - scenario: ember-lts-3.20
            browser: Firefox
            bootstrap: 3
          - scenario: ember-lts-3.20
            browser: Firefox
            bootstrap: 4
          - scenario: ember-lts-3.20
            browser: Firefox
            bootstrap: 5
          - scenario: node-tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Test
        run: yarn ember try:one ${{ matrix.scenario }} --- ember test --launch ${{ matrix.browser }}
        env:
          BOOTSTRAPVERSION: ${{ matrix.bootstrap }}
